#include "autopick/autopick-keys-table.h"
#include "locale/language-switcher.h"

const std::map<AutopickKey, std::string_view> autopick_keys = {
    { AutopickKey::ALL, _("すべての", "all") },
    { AutopickKey::UNAWARE, _("未判明の", "unaware") },
    { AutopickKey::UNIDENTIFIED, _("未鑑定の", "unidentified") },
    { AutopickKey::IDENTIFIED, _("鑑定済みの", "identified") },
    { AutopickKey::STAR_IDENTIFIED, _("*鑑定*済みの", "*identified*") },
    { AutopickKey::COLLECTING, _("収集中の", "collecting") },
    { AutopickKey::ARTIFACT, _("アーティファクト", "artifact") },
    { AutopickKey::EGO, _("エゴ", "ego") },
    { AutopickKey::GOOD, _("上質の", "good") },
    { AutopickKey::NAMELESS, _("無銘の", "nameless") },
    { AutopickKey::AVERAGE, _("並の", "average") },
    { AutopickKey::WORTHLESS, _("無価値の", "worthless") },
    { AutopickKey::RARE, _("レアな", "rare") },
    { AutopickKey::COMMON, _("ありふれた", "common") },
    { AutopickKey::BOOSTED, _("ダイス目の違う", "dice boosted") },
    { AutopickKey::MORE_THAN, _("ダイス目", "more than") },
    { AutopickKey::DICE, _("以上の", "dice") },
    { AutopickKey::MORE_BONUS, _("修正値", "more bonus than") },
    { AutopickKey::MORE_BONUS2, _("以上の", "") },
    { AutopickKey::WANTED, _("賞金首の", "wanted") },
    { AutopickKey::UNIQUE, _("ユニーク・モンスターの", "unique monster's") },
    { AutopickKey::HUMAN, _("人間の", "human") },
    { AutopickKey::UNREADABLE, _("読めない", "unreadable") },
    { AutopickKey::REALM1, _("第一領域の", "first realm's") },
    { AutopickKey::REALM2, _("第二領域の", "second realm's") },
    { AutopickKey::FIRST, _("1冊目の", "first") },
    { AutopickKey::SECOND, _("2冊目の", "second") },
    { AutopickKey::THIRD, _("3冊目の", "third") },
    { AutopickKey::FOURTH, _("4冊目の", "fourth") },
    { AutopickKey::ITEMS, _("アイテム", "items") },
    { AutopickKey::WEAPONS, _("武器", "weapons") },
    { AutopickKey::FAVORITE_WEAPONS, _("得意武器", "favorite weapons") },
    { AutopickKey::ARMORS, _("防具", "armors") },
    { AutopickKey::MISSILES, _("矢", "missiles") },
    { AutopickKey::DEVICES, _("魔法アイテム", "magical devices") },
    { AutopickKey::LIGHTS, _("光源", "lights") },
    { AutopickKey::JUNKS, _("がらくた", "junk") },
    { AutopickKey::CORPSES, _("死体や骨", "corpses or skeletons") },
    { AutopickKey::SPELLBOOKS, _("魔法書", "spellbooks") },
    { AutopickKey::HAFTED, _("鈍器", "hafted weapons") },
    { AutopickKey::SHIELDS, _("盾", "shields") },
    { AutopickKey::BOWS, _("弓", "bows") },
    { AutopickKey::RINGS, _("指輪", "rings") },
    { AutopickKey::AMULETS, _("アミュレット", "amulets") },
    { AutopickKey::SUITS, _("鎧", "suits") },
    { AutopickKey::CLOAKS, _("クローク", "cloaks") },
    { AutopickKey::HELMS, _("兜", "helms") },
    { AutopickKey::GLOVES, _("籠手", "gloves") },
    { AutopickKey::BOOTS, _("靴", "boots") },
};
